added sold training tickets to conference admin stats
EuroPython/epcon pull request #726
Opened 2018-07-11 16:14 UTC by artcz

2018-07-16 09:33 UTC, matrixise approved these changes

2018-07-16 09:33 UTC, matrixise commented on tests/common_tools.py
> +        **kwargs
in the csv export for the accountant, we check if the user is a staff member. I think we will fix some tests ;-)

2018-07-16 09:33 UTC, matrixise commented on tests/test_conference_stats_in_admin.py
> +    assert response.status_code == HTTP_OK_200
add the test when the user is not an admin ;-)

2018-07-16 09:41 UTC, matrixise requested changes

2018-07-16 09:41 UTC, matrixise commented on tests/test_conference_stats_in_admin.py
> +    make_user(is_staff=False)
I prefer

```python
user = make_user(is_staff=False, password='joedoe')
client.login(email=user.email, password='joedoe')
```
and you?

2018-07-16 11:04 UTC, artcz commented on tests/test_conference_stats_in_admin.py
> +    make_user(is_staff=False)
fixed

2019-09-05 21:28 UTC, umgelurgel commented
This seems to have been implemented separately, it's available as of ep2019.

2019-09-05 21:28 UTC, closed without merging